version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /client
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /plugins
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /plugins/src/azure_functions
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /plugins/src/lowpass_filter
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /plugins/src/markos_detector
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /plugins/src
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /plugins/src/simple_detector
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /plugins/src/template_plugin
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tools/metadata_loader
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tools/pmtiles
    schedule:
      interval: daily
