version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: saturday
    # Create a group of dependencies to be updated together in one pull request
    groups:
      # Specify a name for the group, which will be used in pull request titles and branch names
      github-actions-repo-wide:
        # Define patterns to include dependencies in the group (based on dependency name)
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
      day: saturday
    groups:
      docker-root-repo:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /client
    schedule:
      interval: monthly
      day: saturday
    groups:
      docker-client:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /plugins
    schedule:
      interval: monthly
      day: saturday
    groups:
      docker-plugins:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
      day: sunday
    groups:
      npm-client:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: monthly
      day: sunday
    groups:
      npm-e2e:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /plugins/src
    schedule:
      interval: monthly
      day: sunday
    groups:
      pip-plugins:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
      day: sunday
    groups:
      pip-api:
        patterns:
          - "*"
