version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /client
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /plugins
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /plugins/src
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: daily
