APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
DEFAULT_BRANCH: main
IGNORE_GENERATED_FILES: true
VALIDATE_ALL_CODEBASE: false
IGNORE_GITIGNORED_FILES: true
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_CONFIG_FILE: client/.prettierrc
TYPESCRIPT_PRETTIER_CONFIG_FILE: client/.prettierrc
JSON_PRETTIER_CONFIG_FILE: client/.prettierrc
YAML_PRETTIER_CONFIG_FILE: client/.prettierrc
EXCLUDED_DIRECTORIES:
  - megalinter-reports
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - ARM_ARM_TTK
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - BICEP_BICEP_LINTER
  - CLOUDFORMATION_CFN_LINT
  - CSS_STYLELINT
  - CSS_SCSS_LINT
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - ENV_DOTENV_LINTER
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - HTML_DJLINT
  - HTML_HTMLHINT
  - JAVASCRIPT_ES
  - JAVASCRIPT_STANDARD
  - JAVASCRIPT_PRETTIER
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - JSON_V8R
  - JSON_PRETTIER
  - JSON_NPM_PACKAGE_JSON_LINT
  - JSX_ESLINT
  - KUBERNETES_KUBECONFORM
  - KUBERNETES_HELM
  - KUBERNETES_KUBESCAPE
  - MAKEFILE_CHECKMAKE
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - OPENAPI_SPECTRAL
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
  - SPELL_PROSELINT
  - SPELL_VALE
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAGRUNT
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_KICS
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - CREDENTIALS_SECRETLINT
  - DOCKERFILE_DOCKERFILELINT
  - GIT_GIT_DIFF
  - KUBERNETES_KUBEVAL
  - SPELL_MISSPELL

PRE_COMMANDS:
  - command: pip install -r api/requirements.txt
    cwd: workspace
