APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
DEFAULT_BRANCH: main
IGNORE_GENERATED_FILES: true
VALIDATE_ALL_CODEBASE: false
IGNORE_GITIGNORED_FILES: true
JAVASCRIPT_DEFAULT_STYLE: prettier
COPYPASTE_JSCPD_DISABLE_ERRORS: true
SPELL_CSPELL_DISABLE_ERRORS: true
CLEAR_REPORT_FOLDER: true
PYTHON_FLAKE8_CONFIG_FILE: .github/linters/.flake8
PYTHON_RUFF_CONFIG_FILE: .github/linters/.ruff.toml
PYTHON_PYRIGHT_CONFIG_FILE: .github/linters/pyrightconfig.json
PYTHON_MYPY_CONFIG_FILE: .github/linters/.mypy.ini
CSS_STYLELINT_CONFIG_FILE: .github/linters/.stylelintrc.js
DOCKERFILE_HADOLINT_CONFIG_FILE: .github/linters/.hadolint.yaml
GITHUB_COMMENT_REPORTER: false
EXCLUDED_DIRECTORIES:
  - megalinter-reports
  - node_modules
  - venv
DISABLE:
  - ANSIBLE
  - ARM
  - CPP
  - CSHARP
  - CLOJURE
  - PERL
  - PHP
  - POWERSHELL
  - GHERKIN
  - GO
  - COFFEE
  - CLOUDFORMATION
  - R
  - RAKU
  - VBDOTNET

DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_GOODCHECK
  - REPOSITORY_SECRETLINT
  - REPOSITORY_SEMGREP
  - REPOSITORY_SYFT
  - REPOSITORY_TRIVY
  - PYTHON_PYLINT

PRE_COMMANDS:
  - command: |
      pip install -r api/requirements.txt
    cwd: workspace
