---
version: '3.2'

services:
  iqengine:
    image: ghcr.io/iqengine/iqengine:latest
    environment:
      IQENGINE_PLUGINS: '[{"name": "BuiltIn",  "url": "plugins:8000"}]'
      IQENGINE_METADATA_DB_CONNECTION_STRING: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017
    depends_on:
      - mongo
    ports:
      - 3000:3000
  plugins:
    image: ghcr.io/iqengine/plugins:latest
    depends_on:
      - mongo
    ports:
      - 8000:8000
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - ${MONGO_DATASOURCE}:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
