// Copyright (c) 2022 Microsoft Corporation
// Copyright (c) 2023 Marc Lichtman
// Licensed under the MIT License

export const UPDATE_CONNECTION_ACCOUNT_NAME = 'UPDATE_CONNECTION_ACCOUNT_NAME';
export const UPDATE_CONNECTION_CONTAINER_NAME = 'UPDATE_CONNECTION_CONTAINER_NAME';
export const UPDATE_CONNECTION_SAS_TOKEN = 'UPDATE_CONNECTION_SAS_TOKEN';
export const UPDATE_CONNECTION_RECORDING = 'UPDATE_CONNECTION_RECORDING';
export const UPDATE_CONNECTION_META_FILE_HANDLE = 'UPDATE_CONNECTION_META_FILE_HANDLE';
export const UPDATE_CONNECTION_DATA_FILE_HANDLE = 'UPDATE_CONNECTION_DATA_FILE_HANDLE';
export const UPDATE_CONNECTION_BLOB_CLIENT = 'UPDATE_CONNECTION_BLOB_CLIENT';
export const RESET_CONNECTION_OBJ = 'RESET_CONNECTION_OBJ';
