// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export const FETCH_RECORDINGS_LIST_DATA_LOADING = 'FETCH_RECORDINGS_LIST_DATA_LOADING';
export const FETCH_RECORDINGS_LIST_DATA_SUCCESS = 'FETCH_RECORDINGS_LIST_DATA_SUCCESS';
export const FETCH_RECORDINGS_LIST_DATA_FAILURE = 'FETCH_RECORDINGS_LIST_DATA_FAILURE';
