# small image for plugins without gnu radio
FROM python:3.11-slim
LABEL org.opencontainers.image.description="Plugins for IQEngine to provide additional post processing capabilities"
LABEL org.opencontainers.image.licenses=MIT

WORKDIR /src

# Python stuff
COPY src/requirements.txt .
RUN pip install -r requirements.txt --break-system-packages

COPY src .



EXPOSE 8000
CMD uvicorn --host 0.0.0.0 --port 8000  plugins_api:app
