site_name: Vita49 to SigMF Converter

theme:
  name: "material"

plugins:
- search
- mkdocstrings

nav:
  - Vita49 to SigMF Converter: index.md
  - Readme: readme.md
  - requirements: requirements.md
#  - tutorials: tutorials.md
#  - how-to-guides: how-to-guides.md
  - vita49: vita49.md
  - Converter: Converter.md
  - vita49_data_input: vita49_data_input.md
#  - explanation: explanation.md 
