---
name: Periodic Test of Prod

on:
  schedule:
    # 3:20 AM UTC = 11:20 PM EST every day
    - cron: "20 3 * * *"

permissions:
  contents: read

jobs:
  playwright:
    name: RunPlaywrightTests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: e2e
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      - name: Run Playwright tests on Prod
        working-directory: e2e
        run: |
          npx playwright test --config playwright-prod.config.ts
