---
name: Periodic Test of Prod

on:
  schedule:
    # 3:20 AM UTC = 11:20 PM EST every day
    - cron: "20 3 * * *"

permissions:
  contents: read

jobs:
  playwright:
    name: RunPlaywrightTests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: e2e
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      - name: Run Playwright tests on Prod
        working-directory: e2e
        run: |
          npx playwright test --config playwright-prod.config.ts
