---
name: Periodic Test of Prod

on:
  schedule:
    # 3:20 AM UTC = 11:20 PM EST every day
    - cron: "20 3 * * *"

permissions:
  contents: read

jobs:
  playwright:
    name: RunPlaywrightTests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: e2e
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      - name: Run Playwright tests on Prod
        working-directory: e2e
        run: |
          npx playwright test --config playwright-prod.config.ts
