name: Run client tests

on:
  pull_request:
    # only runs on PRs that target main
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vitest:
    name: RunVITests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Node.js version
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: '18.x'

      - name: Run vite tests
        working-directory: client
        run: |
          npm install
          npm run test
        env:
          CI: false
