---
name: Deploy To Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create_pre_release:
    uses: ./.github/workflows/docker-pre-release.yml
    permissions:
      contents: write
      pull-requests: write
      packages: write

  run_staging_deployment:
    if: github.repository == 'IQEngine/IQEngine'
    needs: create_pre_release
    permissions:
      contents: write
      pull-requests: write
      packages: write
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'
      url: https://staging.iqengine.org
    env:
      repository: ${{needs.create_pre_release.outputs.repository}}
      sha: ${{needs.create_pre_release.outputs.sha}}
    steps:
      - name: Log in with Azure with Service Principal
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.AZURE_RESOURCEGROUP }}
          imageToDeploy: ghcr.io/${{ env.repository }}:${{ env.sha}}
