---
name: Run client tests

on:
  pull_request:
    # only runs on PRs that target main
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vitest:
    name: RunVITests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Node.js version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18.x'

      - name: Run vite tests
        working-directory: client
        run: |
          npm install
          npm run test
        env:
          CI: false
