---
name: Run client tests

on:
  pull_request:
    # only runs on PRs that target main
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vitest:
    name: RunVITests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Node.js version
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: '18.x'

      - name: Run vite tests
        working-directory: client
        run: |
          npm install
          npm run test
        env:
          CI: false
