name: A workflow for ensuring credentials are not pushed
on: push
jobs:
  build:
    name: Trufflehog Cred Checker
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@master
       - name: trufflehog-actions-scan
         uses: trufflesecurity/trufflehog@v3.34.0