name: Cred Checker
on: push
jobs:
  build:
    name: Trufflehog Cred Checker
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@master
       - name: trufflehog-actions-scan
         uses: edplato/trufflehog-actions-scan@v0.9l-beta
 